# This is a basic workflow to help you get started with Actions

name: "CI-NuGet"

# Controls when the workflow will run
on:
  # Triggers the workflow on push/pull events but only for the upcoming-nuget-release branch
  push:
    branches: [ upcoming-nuget-release ]
    
jobs:

  PCServer:
    runs-on: ubuntu-latest
    environment: CI
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Build the project
        run: |
          dotnet restore OTAPI.Mods.sln
          dotnet restore OTAPI.Server.Launcher.sln
          dotnet build OTAPI.Mods.sln
          cd OTAPI.Patcher/bin/Debug/net6.0
          dotnet run --project ../../../OTAPI.Patcher.csproj -patchTarget=p -latest=n --framework net6.0
          cd ../../../../
          dotnet build OTAPI.Server.Launcher.sln
          cd OTAPI.Server.Launcher/bin/Debug/net6.0
          dotnet OTAPI.Server.Launcher.dll -test-init

      - uses: actions/upload-artifact@v3
        with:
          name: PC NuGet Package
          path:  OTAPI.Patcher/bin/Debug/net6.0/OTAPI.PC.nupkg

      - uses: actions/upload-artifact@v3
        with:
          name: PC Binaries
          path: |
            OTAPI.Patcher/bin/Debug/net6.0/artifact-pc/COPYING.txt
            OTAPI.Patcher/bin/Debug/net6.0/artifact-pc/OTAPI.dll
            OTAPI.Patcher/bin/Debug/net6.0/artifact-pc/OTAPI.Runtime.dll

      - uses: actions/upload-artifact@v3
        with:
          name: PC Wiki MD files
          path: OTAPI.Patcher/bin/Debug/net6.0/OTAPI.PC.Server.mfw.md

      - name: "Releasing to NuGet: OTAPI.Upcoming"
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push OTAPI.Patcher/bin/Debug/net6.0/OTAPI.PC.nupkg --source https://api.nuget.org/v3/index.json --api-key "$env:NUGET_API_KEY"

  MobileServer:
    runs-on: ubuntu-latest
    environment: CI
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Build the project
        run: |
          dotnet restore OTAPI.Mods.sln
          dotnet restore OTAPI.Server.Launcher.sln
          dotnet build OTAPI.Mods.sln
          cd OTAPI.Patcher/bin/Debug/net6.0
          dotnet run --project ../../../OTAPI.Patcher.csproj -patchTarget=m -latest=n --framework net6.0
          cd ../../../../
          dotnet build OTAPI.Server.Launcher.sln
          cd OTAPI.Server.Launcher/bin/Debug/net6.0
          dotnet OTAPI.Server.Launcher.dll -test-init

      - uses: actions/upload-artifact@v3
        with:
          name: Mobile NuGet Package
          path: OTAPI.Patcher/bin/Debug/net6.0/OTAPI.Mobile.nupkg

      - uses: actions/upload-artifact@v3
        with:
          name: Mobile Binaries
          path: |
            OTAPI.Patcher/bin/Debug/net6.0/artifact-mobile/COPYING.txt
            OTAPI.Patcher/bin/Debug/net6.0/artifact-mobile/OTAPI.dll
            OTAPI.Patcher/bin/Debug/net6.0/artifact-mobile/OTAPI.Runtime.dll

      - uses: actions/upload-artifact@v3
        with:
          name: Mobile Wiki MD files
          path: OTAPI.Patcher/bin/Debug/net6.0/OTAPI.Mobile.Server.mfw.md

      - name: "Releasing to NuGet: OTAPI.Upcoming.Mobile"
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push OTAPI.Patcher/bin/Debug/net6.0/OTAPI.Mobile.nupkg --source https://api.nuget.org/v3/index.json --api-key "$env:NUGET_API_KEY"

  tModLoaderServer:
    runs-on: ubuntu-latest
    environment: CI
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Build the project
        run: |
          dotnet restore OTAPI.Mods.sln
          dotnet restore OTAPI.Server.Launcher.sln
          dotnet build OTAPI.Mods.sln
          cd OTAPI.Patcher/bin/Debug/net6.0
          dotnet run --project ../../../OTAPI.Patcher.csproj -patchTarget=t -latest=n --framework net6.0
          cd ../../../../
          dotnet build OTAPI.Server.Launcher.sln
          cd OTAPI.Server.Launcher/bin/Debug/net6.0
          dotnet OTAPI.Server.Launcher.dll -test-init

      - uses: actions/upload-artifact@v3
        with:
          name: tModLoader NuGet Package
          path: OTAPI.Patcher/bin/Debug/net6.0/OTAPI.TML.nupkg

      - uses: actions/upload-artifact@v3
        with:
          name: tModLoader Binaries
          path: |
            OTAPI.Patcher/bin/Debug/net6.0/artifact-tml/COPYING.txt
            OTAPI.Patcher/bin/Debug/net6.0/artifact-tml/OTAPI.dll
            OTAPI.Patcher/bin/Debug/net6.0/artifact-tml/OTAPI.Runtime.dll

      - uses: actions/upload-artifact@v3
        with:
          name: tModLoader Wiki MD files
          path: OTAPI.Patcher/bin/Debug/net6.0/OTAPI.TML.PC.Server.mfw.md
          
      - name: "Releasing to NuGet: OTAPI.Upcoming.tModLoader"
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push OTAPI.Patcher/bin/Debug/net6.0/OTAPI.TML.nupkg --source https://api.nuget.org/v3/index.json --api-key "$env:NUGET_API_KEY"
